name: 'Build and Test'

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && format('{0}-{1}', github.workflow, github.sha) || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never

jobs:
  build:
    name: 'Build (Java 17)'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    # A possible workaround for <https://github.com/dorny/test-reporter/issues/168>.
    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
      # Explicitly granted, necessary for the `publish` step.
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Git tags, so that semantic version can be calculated.
          # Alternatively, run `git fetch --prune --unshallow --tags` as the
          # next step, see
          # https://github.com/actions/checkout/issues/206#issuecomment-607496604.
          fetch-depth: 0

      - name: 'Set up Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk+fx

      - name: 'Cache ~/.konan'
        id: cache-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-build-java17
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-
            ${{ runner.os }}-konan-

      - name: 'Execute Gradle build'
        id: build
        uses: gradle/gradle-build-action@v3.4.2
        with:
          gradle-version: wrapper
          arguments: |
            build
            allTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
